name: Test
on:
  push:
jobs:
  run-tests:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2

      - run: mkdir build

      - name: Build Project
        uses: threeal/cmake-action@v2.1.0

      - name: Run Tests
        run: cd build && ./check_gbe
