name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y libsdl2-{,ttf-}dev build-essential, cmake, check

      - run: ls -clash cmake/

      - name: Build Project
        uses: threeal/cmake-action@v2.1.0

      - name: Run Tests
        run: cd build && make && ./tests/check_gbe
