name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
        with:
          submodules: true

      - run: mkdir build

      - name: Build Project
        uses: threeal/cmake-action@v2.1.0

      - name: Run Tests
        run: cd build && ./check_gbe
